version: 2.0

jobs:
  build-deploy-python2: # build for the master branch
    machine: true
    working_directory: ~/selenium-firefox
    steps:
      - checkout
      - run:
          name: Build python 2 docker image and push to repo
          command: |
            docker version
            docker build -t "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python2-latest .
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python2-latest
  build-deploy-python3: # build for the master branch
    machine: true
    working_directory: ~/selenium-firefox
    steps:
      - checkout
      - run:
          name: Build python 3 docker image and push to repo
          command: |
            docker version
            docker build -f Dockerfile.python3 -t "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python3-latest .
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python3-latest
workflows:
  version: 2
  build-push:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-deploy-python2
      - build-deploy-python3
