version: 2.0

jobs:
  build-deploy: # build for the master branch
    machine: true
    working_directory: ~/selenium-firefox
    steps:
      - checkout
      - run:
          name: Build docker image and push to repo
          command: |
            docker version
            docker build -t "${DOCKERHUB_USER}":latest .
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":latest
workflows:
  version: 2
  build-push:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-deploy
