version: 2.0

jobs:
  build-deploy-python3: # build for the master branch
    machine: true
    working_directory: ~/selenium-firefox
    steps:
      - checkout
      - run:
          name: Build python 3 docker image and push to repo
          command: |
            docker version
            docker build -f Dockerfile.python3 -t "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python3-latest .
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python3-latest
  build-deploy-python3-release: # build for the master branch
    machine: true
    working_directory: ~/selenium-firefox
    steps:
      - checkout
      - run:
          name: Build python 3 docker image and push to repo
          command: |
            docker version
            docker build -f Dockerfile.python3 -t "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python3-release-latest .
            docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
            docker push "${DOCKERHUB_USER}"/"${DOCKERHUB_REPO}":python3-release-latest
workflows:
  version: 2
  build-push-nightly:
    triggers:
      - schedule:
          cron: "0 0 15 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-deploy-python3
  build-push-release:
    jobs:
      - build-deploy-python3-release:
          requires:
            - build_approval
      - build_approval:
          type: approval
